//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniverseLanWizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniverseLanWizard.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c43868d224035dad66357a6852f1964309fe7597=1.100.2_Windows_MSVC15_32bit|4329984
        ///c49d2bc610f5fa8924a2430edc84a27c55e66ca4=1.101_Windows_MSVC17_32bit|4421120
        ///52c87a936b71e0349cff92dfdbbc7889f24edb65=1.103_Windows_MSVC16_32bit|4419584
        ///f04517f0adef0762e55d05ef9d09be769de9c6dc=1.104.2_Windows_MSVC18_32bit|4270592
        ///b8c3c2b58224b27e2fc8e59f97ff52a2c84fcb3a=1.104.5_Windows_MSVC16_32bit|4339712
        ///d2719d0616ff1e96023f46ffaf1de5b91f5d8e00=1.106_Windows_MSVC15_32bit|4346368
        ///cd20150c573fca9ee0ffce510c6aebfa44735e97=1.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sha1_hashes {
            get {
                return ResourceManager.GetString("sha1_hashes", resourceCulture);
            }
        }
    }
}
