#pragma once

enum ePedRootBoneTagsV
{
	ROOTBONETAG_RIGHTFOOTFRONT = 0x60E6,
	ROOTBONETAG_LEFTFOOTBACK = 0x3779,
	ROOTBONETAG_RIGHTFOOTBACK = 0xCC4D,
	ROOTBONETAG_LEFTHAND = 0x49D9,
	ROOTBONETAG_RIGHTHAND = 0xDEAD,
	ROOTBONETAG_STOMACH = 0x60F0,
	ROOTBONETAG_HEAD = 0x796E,
	ROOTBONETAG_NECK = 0x9995,
};

enum ePedBoneTagsV
{
	BONETAG_RIGHTFOOTFRONT = ROOTBONETAG_RIGHTFOOTFRONT,
	BONETAG_LEFTFOOTBACK = ROOTBONETAG_LEFTFOOTBACK,
	BONETAG_RIGHTFOOTBACK = ROOTBONETAG_RIGHTFOOTBACK,
	BONETAG_LEFTHAND = ROOTBONETAG_LEFTHAND,
	BONETAG_RIGHTHAND = ROOTBONETAG_RIGHTHAND,
	BONETAG_STOMACH = ROOTBONETAG_STOMACH,
	BONETAG_HEAD = ROOTBONETAG_HEAD,
	BONETAG_NECK = ROOTBONETAG_NECK,

	BONETAG_ROOT = 0x0000,
	BONETAG_PELVIS = 0x2E28,
	BONETAG_L_THIGH = 0xE39F,
	BONETAG_R_THIGH = 0xCA72,
	BONETAG_L_CALF = 0xF9BB,
	BONETAG_R_CALF = 0x9000,
	BONETAG_L_CLAVICLE = 0xFCD9,
	BONETAG_R_CLAVICLE = 0x29D2,
	BONETAG_L_UPPERARM = 0xB1C5,
	BONETAG_R_UPPERARM = 0x9D4D,
	BONETAG_L_FOREARM = 0xEEEB,
	BONETAG_R_FOREARM = 0x6E5C,
};
